### PR TITLE
Remove TenUp__ from class names - Fixes #2

### LINKED ISSUE #2: Let's not use TenUp in the class names
Unless there's a need for this: `.TenUp__navigation__menu` let's avoid it, it's just overly long and the demos already use .site-navigation, I think

### PR DESCRIPTION
**Pull request by garand**

### CODE REVIEW

**Review by timwright12 — CHANGES_REQUESTED** [review]
Why aren't we hooking into the natural HTML classes WordPress gives us? This makes the menu break without JS enabled and can cause flickering as the scripting loads.

**Comment by garand** [comment]
That's a good questions... should be fixed for sure. I had thought that's how it had originally been implemented. Are you okay with merging this in and handling that in a [separate issue](https://github.com/10up/component-navigation/issues/4)?

**Review by timwright12 — CHANGES_REQUESTED** [review]
This still isn't quite right, the menu should fully function on large and small screens without JavaScript enabled like the current one: https://10up.github.io/wp-component-library/component/responsive-navigation/example.html

Right now this PR defaults to have all the nav items displayed and broken-looking

**Comment by timwright12** [comment]
Looks good, I updated the packages and fixed one small linting error that popped up

**Pull request merged**
